packages:
  - packages/*
  - packages/search/*
  - packages/spill/*
  - apps/*

onlyBuiltDependencies:
  - esbuild
allowBuilds:
  electron-winstaller: false
  esbuild: true
minimumReleaseAgeExclude:
  - tnega@0.1.1
