import { defineTheme } from '@astryxdesign/core/theme'
import { neutralTheme } from '@astryxdesign/theme-neutral'

/** Studio palette. All legacy surfaces resolve through these same tokens. */
export const studioTheme = defineTheme({
  name: 'tnega-studio',
  extends: neutralTheme,
  color: { accent: ['#267466', '#91c7b8'], neutralStyle: 'warm' },
  typography: {
    scale: { base: 14, ratio: 1.2 },
    body: { family: 'Inter', fallbacks: "'Segoe UI', 'Microsoft YaHei', sans-serif" },
  },
  tokens: {
    '--color-background-body': ['#eeefeb', '#171b1a'],
    '--color-background-surface': ['#fafbf8', '#202524'],
    '--color-background-card': ['#ffffff', '#282e2c'],
    '--color-background-popover': ['#ffffff', '#282e2c'],
    '--color-text-primary': ['#25312d', '#e5eae6'],
    '--color-text-secondary': ['#627069', '#a6b3ab'],
    '--color-accent': ['#267466', '#91c7b8'],
    '--color-success': ['#367857', '#9ccbaf'],
    '--color-warning': ['#946722', '#dfbd80'],
    '--color-error': ['#b44140', '#f0a4a0'],
    '--color-icon-primary': ['#25312d', '#e5eae6'],
    '--color-icon-secondary': ['#627069', '#a6b3ab'],
    '--color-border': ['#dce2db', '#36403a'],
    '--radius-container': '16px',
  },
  localTokens: {
    '--canvas': 'var(--color-background-surface)',
    '--sidebar': 'var(--color-background-body)',
    '--surface-card': 'var(--color-background-card)',
    '--surface-soft': 'var(--color-background-muted)',
    '--user-bubble': ['#e5eee7', '#303e36'],
    '--user-ink': 'var(--color-text-primary)',
    '--ink': 'var(--color-text-primary)',
    '--body': 'var(--color-text-primary)',
    '--mute': 'var(--color-text-secondary)',
    '--stone': 'var(--color-text-secondary)',
    '--hairline': 'var(--color-border)',
    '--accent': 'var(--color-text-accent)',
    '--danger': ['#b44140', '#f0a4a0'],
    '--warning': ['#946722', '#dfbd80'],
    '--success': ['#367857', '#9ccbaf'],
    '--astryx-theme-neutral-color-status-fill-accent': 'var(--color-accent)',
    '--astryx-theme-neutral-color-status-fill-success': 'var(--color-success)',
    '--astryx-theme-neutral-color-status-fill-warning': 'var(--color-warning)',
    '--astryx-theme-neutral-color-status-fill-error': 'var(--color-error)',
  },
  components: {
    'top-nav': { base: { backgroundColor: 'var(--color-background-body)' } },
    'side-nav': { base: { backgroundColor: 'var(--color-background-body)' } },
    'chat-message-bubble': { base: { fontSize: 'var(--font-size-base)', lineHeight: '1.75' } },
  },
})
